# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\rrobonix.audio\"V\n\nAudioChunk\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08sequence\x18\x03 \x01(\r\x12\x12\n\nduration_s\x18\x04 \x01(\x02\"b\n\x0b\x41udioConfig\x12\x10\n\x08\x65ncoding\x18\x01 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\r\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x17\n\x0f\x62its_per_sample\x18\x04 \x01(\r\"i\n\x0b\x41udioDevice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x12\n\nis_default\x18\x04 \x01(\x08\x12\x10\n\x08\x63hannels\x18\x05 \x01(\r\x12\x0c\n\x04note\x18\x06 \x01(\t\"\x1c\n\x1aGetAudioBridgeInfo_Request\"c\n\x1bGetAudioBridgeInfo_Response\x12\x0f\n\x07reverse\x18\x01 \x01(\x08\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x11\n\tconnected\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"\x1a\n\x18ListAudioDevices_Request\"}\n\x19ListAudioDevices_Response\x12+\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x1a.robonix.audio.AudioDevice\x12\x18\n\x10\x63urrent_input_id\x18\x02 \x01(\t\x12\x19\n\x11\x63urrent_output_id\x18\x03 \x01(\t\"5\n\x19SelectAudioDevice_Request\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"7\n\x1aSelectAudioDevice_Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=30
  _globals['_AUDIOCHUNK']._serialized_end=116
  _globals['_AUDIOCONFIG']._serialized_start=118
  _globals['_AUDIOCONFIG']._serialized_end=216
  _globals['_AUDIODEVICE']._serialized_start=218
  _globals['_AUDIODEVICE']._serialized_end=323
  _globals['_GETAUDIOBRIDGEINFO_REQUEST']._serialized_start=325
  _globals['_GETAUDIOBRIDGEINFO_REQUEST']._serialized_end=353
  _globals['_GETAUDIOBRIDGEINFO_RESPONSE']._serialized_start=355
  _globals['_GETAUDIOBRIDGEINFO_RESPONSE']._serialized_end=454
  _globals['_LISTAUDIODEVICES_REQUEST']._serialized_start=456
  _globals['_LISTAUDIODEVICES_REQUEST']._serialized_end=482
  _globals['_LISTAUDIODEVICES_RESPONSE']._serialized_start=484
  _globals['_LISTAUDIODEVICES_RESPONSE']._serialized_end=609
  _globals['_SELECTAUDIODEVICE_REQUEST']._serialized_start=611
  _globals['_SELECTAUDIODEVICE_REQUEST']._serialized_end=664
  _globals['_SELECTAUDIODEVICE_RESPONSE']._serialized_start=666
  _globals['_SELECTAUDIODEVICE_RESPONSE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
