# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pilot_pb2 as pilot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x10robonix.executor\x1a\x0bpilot.proto\"j\n\x0e\x43\x61pabilitySpec\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x19\n\x11input_schema_json\x18\x04 \x01(\t\"\x8b\x02\n\tRtdlEvent\x12\x12\n\nevent_kind\x18\x01 \x01(\r\x12\x37\n\x0cplan_started\x18\x02 \x01(\x0b\x32!.robonix.executor.RtdlPlanStarted\x12\x30\n\nnode_state\x18\x03 \x01(\x0b\x32\x1c.robonix.pilot.RtdlNodeState\x12\x39\n\rplan_complete\x18\x04 \x01(\x0b\x32\".robonix.executor.RtdlPlanComplete\"D\n\rRtdlEventEnum\x12\x10\n\x0cPLAN_STARTED\x10\x00\x12\x0e\n\nNODE_STATE\x10\x01\x12\x11\n\rPLAN_COMPLETE\x10\x02\"7\n\x10RtdlPlanComplete\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x12\n\nany_failed\x18\x02 \x01(\x08\"\"\n\x0fRtdlPlanStarted\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\"\x13\n\x11\x43\x61ncelAll_Request\"%\n\x12\x43\x61ncelAll_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"d\n\x13\x43ontrolPlan_Request\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0f\n\x07plan_id\x18\x02 \x01(\t\x12\r\n\x05op_id\x18\x03 \x01(\t\x12\x0c\n\x04when\x18\x04 \x01(\t\x12\x0f\n\x07wait_ms\x18\x05 \x01(\x04\"Z\n\x14\x43ontrolPlan_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"4\n\x0f\x45xecute_Request\x12!\n\x04plan\x18\x01 \x01(\x0b\x32\x13.robonix.pilot.Plan\">\n\x10\x45xecute_Response\x12*\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1b.robonix.executor.RtdlEvent\"\x19\n\x17ListActivePlans_Request\"N\n\x18ListActivePlans_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nplans_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITYSPEC']._serialized_start=49
  _globals['_CAPABILITYSPEC']._serialized_end=155
  _globals['_RTDLEVENT']._serialized_start=158
  _globals['_RTDLEVENT']._serialized_end=425
  _globals['_RTDLEVENT_RTDLEVENTENUM']._serialized_start=357
  _globals['_RTDLEVENT_RTDLEVENTENUM']._serialized_end=425
  _globals['_RTDLPLANCOMPLETE']._serialized_start=427
  _globals['_RTDLPLANCOMPLETE']._serialized_end=482
  _globals['_RTDLPLANSTARTED']._serialized_start=484
  _globals['_RTDLPLANSTARTED']._serialized_end=518
  _globals['_CANCELALL_REQUEST']._serialized_start=520
  _globals['_CANCELALL_REQUEST']._serialized_end=539
  _globals['_CANCELALL_RESPONSE']._serialized_start=541
  _globals['_CANCELALL_RESPONSE']._serialized_end=578
  _globals['_CONTROLPLAN_REQUEST']._serialized_start=580
  _globals['_CONTROLPLAN_REQUEST']._serialized_end=680
  _globals['_CONTROLPLAN_RESPONSE']._serialized_start=682
  _globals['_CONTROLPLAN_RESPONSE']._serialized_end=772
  _globals['_EXECUTE_REQUEST']._serialized_start=774
  _globals['_EXECUTE_REQUEST']._serialized_end=826
  _globals['_EXECUTE_RESPONSE']._serialized_start=828
  _globals['_EXECUTE_RESPONSE']._serialized_end=890
  _globals['_LISTACTIVEPLANS_REQUEST']._serialized_start=892
  _globals['_LISTACTIVEPLANS_REQUEST']._serialized_end=917
  _globals['_LISTACTIVEPLANS_RESPONSE']._serialized_start=919
  _globals['_LISTACTIVEPLANS_RESPONSE']._serialized_end=997
# @@protoc_insertion_point(module_scope)
