# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x0erobonix.health\"v\n\x0bHealthState\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x10\n\x08\x63harging\x18\x02 \x01(\x08\x12\x13\n\x0bremaining_s\x18\x03 \x01(\x03\x12/\n\x08readings\x18\x04 \x03(\x0b\x32\x1d.robonix.health.SensorReading\"j\n\rSensorReading\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06temp_c\x18\x02 \x01(\x02\x12\x0f\n\x07voltage\x18\x03 \x01(\x02\x12\x11\n\tcurrent_a\x18\x04 \x01(\x02\x12\x17\n\x0f\x62\x61ttery_percent\x18\x05 \x01(\x02\"\x18\n\x16GetHealthState_Request\"E\n\x17GetHealthState_Response\x12*\n\x05state\x18\x01 \x01(\x0b\x32\x1b.robonix.health.HealthState\"\x1b\n\x19StreamHealthState_Request\"H\n\x1aStreamHealthState_Response\x12*\n\x05state\x18\x01 \x01(\x0b\x32\x1b.robonix.health.HealthStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSTATE']._serialized_start=32
  _globals['_HEALTHSTATE']._serialized_end=150
  _globals['_SENSORREADING']._serialized_start=152
  _globals['_SENSORREADING']._serialized_end=258
  _globals['_GETHEALTHSTATE_REQUEST']._serialized_start=260
  _globals['_GETHEALTHSTATE_REQUEST']._serialized_end=284
  _globals['_GETHEALTHSTATE_RESPONSE']._serialized_start=286
  _globals['_GETHEALTHSTATE_RESPONSE']._serialized_end=355
  _globals['_STREAMHEALTHSTATE_REQUEST']._serialized_start=357
  _globals['_STREAMHEALTHSTATE_REQUEST']._serialized_end=384
  _globals['_STREAMHEALTHSTATE_RESPONSE']._serialized_start=386
  _globals['_STREAMHEALTHSTATE_RESPONSE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
