# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: module_health_client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'module_health_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amodule_health_client.proto\x12\x1crobonix.client.module_health\"\xc6\x01\n\x0cModuleHealth\x12\x12\n\nmodule_key\x18\x01 \x01(\t\x12\x11\n\tmodule_id\x18\x02 \x01(\t\x12\x13\n\x0bprovider_id\x18\x03 \x01(\t\x12\x0e\n\x06health\x18\x04 \x01(\r\x12\r\n\x05state\x18\x05 \x01(\t\x12\x13\n\x0breason_code\x18\x06 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x07 \x01(\t\x12\x0e\n\x06source\x18\x08 \x01(\t\x12\x16\n\x0ereceived_ts_ns\x18\t \x01(\x04\x12\x0e\n\x06ttl_ms\x18\n \x01(\r\"\x87\x01\n\x14ModuleHealthSnapshot\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\r\n\x05ts_ns\x18\x02 \x01(\x04\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12;\n\x07modules\x18\x04 \x03(\x0b\x32*.robonix.client.module_health.ModuleHealth\"!\n\x1fGetModuleHealthSnapshot_Request\"h\n GetModuleHealthSnapshot_Response\x12\x44\n\x08snapshot\x18\x01 \x01(\x0b\x32\x32.robonix.client.module_health.ModuleHealthSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'module_health_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULEHEALTH']._serialized_start=61
  _globals['_MODULEHEALTH']._serialized_end=259
  _globals['_MODULEHEALTHSNAPSHOT']._serialized_start=262
  _globals['_MODULEHEALTHSNAPSHOT']._serialized_end=397
  _globals['_GETMODULEHEALTHSNAPSHOT_REQUEST']._serialized_start=399
  _globals['_GETMODULEHEALTHSNAPSHOT_REQUEST']._serialized_end=432
  _globals['_GETMODULEHEALTHSNAPSHOT_RESPONSE']._serialized_start=434
  _globals['_GETMODULEHEALTHSNAPSHOT_RESPONSE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
