# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentinel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentinel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esentinel.proto\x12\x10robonix.sentinel\"*\n\x11ListRules_Request\x12\x15\n\rsession_token\x18\x01 \x01(\t\"(\n\x12ListRules_Response\x12\x12\n\nrules_json\x18\x01 \x01(\t\"A\n\x14ReplaceRules_Request\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x12\n\nrules_json\x18\x02 \x01(\t\"+\n\x15ReplaceRules_Response\x12\x12\n\nrules_json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentinel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTRULES_REQUEST']._serialized_start=36
  _globals['_LISTRULES_REQUEST']._serialized_end=78
  _globals['_LISTRULES_RESPONSE']._serialized_start=80
  _globals['_LISTRULES_RESPONSE']._serialized_end=120
  _globals['_REPLACERULES_REQUEST']._serialized_start=122
  _globals['_REPLACERULES_REQUEST']._serialized_end=187
  _globals['_REPLACERULES_RESPONSE']._serialized_start=189
  _globals['_REPLACERULES_RESPONSE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
