# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voiceprint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voiceprint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10voiceprint.proto\x12\x12robonix.voiceprint\")\n\x16\x44\x65leteEnrolled_Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"9\n\x17\x44\x65leteEnrolled_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"r\n\x0e\x45nroll_Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x05 \x01(\r\"1\n\x0f\x45nroll_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"P\n\x10Identify_Request\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\r\"l\n\x11Identify_Response\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08is_known\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"\x16\n\x14ListEnrolled_Request\"I\n\x15ListEnrolled_Response\x12\x12\n\nusers_json\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voiceprint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELETEENROLLED_REQUEST']._serialized_start=40
  _globals['_DELETEENROLLED_REQUEST']._serialized_end=81
  _globals['_DELETEENROLLED_RESPONSE']._serialized_start=83
  _globals['_DELETEENROLLED_RESPONSE']._serialized_end=140
  _globals['_ENROLL_REQUEST']._serialized_start=142
  _globals['_ENROLL_REQUEST']._serialized_end=256
  _globals['_ENROLL_RESPONSE']._serialized_start=258
  _globals['_ENROLL_RESPONSE']._serialized_end=307
  _globals['_IDENTIFY_REQUEST']._serialized_start=309
  _globals['_IDENTIFY_REQUEST']._serialized_end=389
  _globals['_IDENTIFY_RESPONSE']._serialized_start=391
  _globals['_IDENTIFY_RESPONSE']._serialized_end=499
  _globals['_LISTENROLLED_REQUEST']._serialized_start=501
  _globals['_LISTENROLLED_REQUEST']._serialized_end=523
  _globals['_LISTENROLLED_RESPONSE']._serialized_start=525
  _globals['_LISTENROLLED_RESPONSE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
